sudo: required

services:
  - docker

language: go

go:
  - "1.13.x"

env:
  - VERBOSE=1 TEST_SUITE=run-tests-local-process ARANGODB=arangodb:3.3 STARTER_MODES="single,cluster,activefailover"
  - VERBOSE=1 TEST_SUITE=run-tests-docker        ARANGODB=arangodb:3.3 STARTER_MODES="single,cluster,activefailover"
  - VERBOSE=1 TEST_SUITE=run-tests-local-process ARANGODB=arangodb/arangodb:latest STARTER_MODES="single,cluster,activefailover"
  - VERBOSE=1 TEST_SUITE=run-tests-docker        ARANGODB=arangodb/arangodb:latest STARTER_MODES="single,cluster,activefailover"
  - VERBOSE=1 TEST_SUITE=run-tests-local-process ARANGODB=arangodb/arangodb-preview:latest STARTER_MODES="single,cluster,activefailover"
  - VERBOSE=1 TEST_SUITE=run-tests-docker        ARANGODB=arangodb/arangodb-preview:latest STARTER_MODES="single,cluster,activefailover"

script: make $TEST_SUITE

# Install Docker CE
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
